### ISSUE TITLE
Enable Github Pages

### ISSUE THREAD

**Issue by urschrei** [nbsapi/nbsapi#18]
I don't have access to settings, so I can't enable it.

**Comment by hrishiballal** [comment]
Can you please check now?

**Comment by hrishiballal** [comment]
You can use this repo but if better / more useful, we can create a new repository as well.

**Comment by urschrei** [comment]
Should be fine now. Thanks!

**Comment by urschrei** [comment]
FYI https://nbsapi.github.io/nbsapi/ is now being built from the `gh-pages` branch.

**Comment by hrishiballal** [comment]
I have now linked https://nbsapi.org as well to this 🤞
