### ISSUE TITLE
Create a endpoint for Adaptation Impact

### ISSUE THREAD

**Issue by hrishiballal** [nbsapi/nbsapi#40]
It would be nice to have an endpoint where adopters can share the impact of NBS based on their models and outputs. This impact should accommodate something like: categorical `high` , `medium` and `low`. The description could be free text. Additionally there should be something like `measure`, `unit` and `value`. E.g. temperature is decreased by 0.3 degrees Celcius.

**Comment by urschrei** [comment]
Done in #41
